apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: order-gateway-traefik-app-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: order-gateway-traefik-app
    k8s.kuboard.cn/workload: order-gateway-traefik-app
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-oplog@kubernetescrd,
      kube-system-strip-order-gateway-prefix@kubernetescrd,
      kube-system-http-redirect-https@kubernetescrd,
      kube-system-common-headers@kubernetescrd,
      kube-system-headers-appid-to-body@kubernetescrd,
      kube-system-headers-userid-to-body@kubernetescrd,
      kube-system-headers-app-login-token-to-body@kubernetescrd,
      kube-system-app-rbac-auth@kubernetescrd

spec:
  rules:
    - host: api.npool.top
      http: &http_rules
        paths:
          - path: /api/order/v1/version
            backend:
              serviceName: order-gateway
              servicePort: 50430
    - host: api.procyon.vip
      http: *http_rules
    - host: api.xpool.top
      http: *http_rules
    - host: api.ohhash.com
      http: *http_rules
    - host: api.procyon.xpool.top
      http: *http_rules
    - host: api.lpsb.xpool.top
      http: *http_rules
    - host: api.lpsecretbase.com
      http: *http_rules
    - host: api.development.npool.top
      http: *http_rules
    - host: api.hk-cryptomore-production.npool.top
      http: *http_rules
    - host: api.cryptomore.io
      http: *http_rules
    - host: api.epool.tech
      http: *http_rules
    - host: api.xhash.ai
      http: *http_rules
    - host: api.tokyo-xhash-production.npool.top
      http: *http_rules

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: order-gateway-traefik-app-user-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: order-gateway-traefik-app-user
    k8s.kuboard.cn/workload: order-gateway-traefik-app-user
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-oplog@kubernetescrd,
      kube-system-strip-order-gateway-prefix@kubernetescrd,
      kube-system-http-redirect-https@kubernetescrd,
      kube-system-common-headers@kubernetescrd,
      kube-system-headers-appid-to-body@kubernetescrd,
      kube-system-headers-userid-to-body@kubernetescrd,
      kube-system-headers-app-login-token-to-body@kubernetescrd,
      kube-system-app-user-role-rbac-auth@kubernetescrd

spec:
  rules:
    - host: api.npool.top
      http: &http_rules
        paths:
          ######
          # Enable for all users
          ######
          - path: /api/order/v1/create/order
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/update/order
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/get
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/create/simulateorder
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/create/simulateorders
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/get/my/compensates
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/get/my/feeorders
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/get/my/ordercoupons
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/get/my/orders
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/get/my/outofgases
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/get/my/powerrentalorders
            backend:
              serviceName: order-gateway
              servicePort: 50430
          ######
          # Only enable for app admin
          ######
          - path: /api/order/v1/create/user/order
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/create/app/user/order
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/update/user/order
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/update/app/user/order
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/create/simulate/config
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/update/simulate/config
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/get/simulate/config
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/get/simulate/configs
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/create/app/simulate/config
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/update/app/simulate/config
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/get/app/simulate/configs
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/get/app/simulate/config
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/delete/app/simulate/config
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/admin/create/appconfig
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/admin/delete/appconfig
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/admin/get/appconfigs
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/admin/update/appconfig
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/create/appconfig
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/get/appconfig
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/update/appconfig
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/admin/get/compensates
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/get/compensates
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/admin/create/feeorder
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/admin/create/feeorders
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/admin/delete/feeorder
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/admin/get/feeorders
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/admin/update/feeorder
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/create/feeorder
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/create/feeorders
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/create/user/feeorder
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/create/user/feeorders
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/get/feeorder
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/get/feeorders
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/update/feeorder
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/update/user/feeorder
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/admin/get/ordercoupons
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/get/ordercoupons
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/admin/get/orders
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/get/orders
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/admin/get/outofgases
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/get/outofgases
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/admin/create/powerrentalcompensate
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/admin/delete/powerrentalcompensate
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/admin/delete/powerrentaloutofgas
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/admin/create/powerrentalorder
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/admin/delete/powerrentalorder
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/admin/get/powerrentalorders
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/admin/update/powerrentalorder
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/create/powerrentalorder
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/create/user/powerrentalorder
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/get/powerrentalorder
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/get/powerrentalorders
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/update/powerrentalorder
            backend:
              serviceName: order-gateway
              servicePort: 50430
          - path: /api/order/v1/update/user/powerrentalorder
            backend:
              serviceName: order-gateway
              servicePort: 50430
    - host: api.procyon.vip
      http: *http_rules
    - host: api.xpool.top
      http: *http_rules
    - host: api.ohhash.com
      http: *http_rules
    - host: api.procyon.xpool.top
      http: *http_rules
    - host: api.lpsb.xpool.top
      http: *http_rules
    - host: api.jh-testing.npool.top
      http: *http_rules
    - host: api.harbin-testing.npool.top
      http: *http_rules
    - host: api.lpsecretbase.com
      http: *http_rules
    - host: api.development.npool.top
      http: *http_rules
    - host: api.hk-cryptomore-production.npool.top
      http: *http_rules
    - host: api.cryptomore.io
      http: *http_rules
    - host: api.epool.tech
      http: *http_rules
    - host: api.xhash.ai
      http: *http_rules
    - host: api.tokyo-xhash-production.npool.top
      http: *http_rules
